# action.yml
name: 'Hello World'
description: 'test'
inputs:
  YOUR_GITHUB_USER_NAME:
    description: 'your github user name'
    required: true
  YOUR_GITHUB_REPOSITORY:
    description: 'your github repository'
    required: true
  GITHUB_TOKEN:
    description: 'your github repository token'
    required: true
  SNIPPET_GIST_ID:
    description: 'your snippet gist id'
    required: true
  SNIPPET_GIST_TOKEN:
    description: 'your snippet gist token'
    required: true
  SNIPPET_FILE_NAME:
    description: 'your snippet file name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.YOUR_GITHUB_USER_NAME }}
    - ${{ inputs.YOUR_GITHUB_REPOSITORY }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.SNIPPET_GIST_ID }}
    - ${{ inputs.SNIPPET_GIST_TOKEN }}
    - ${{ inputs.SNIPPET_FILE_NAME }}